### ISSUE TITLE
tarballs don't contain test code

### ISSUE THREAD

**Issue by yurivict** [ssandrews/Smoldyn#111]
The [tarball](https://www.smoldyn.org/smoldyn-2.67.tgz) doesn't contain the code for testing:
```
CMake Error at examples/CMakeLists.txt:61 (add_executable):
  Cannot find source file:

    S97_libsmoldyn/testcode/testcode.cpp
```

This makes tarballs unusable for packaging systems which have an option to run tests after build, like FreeBSD ports.

**Comment by ssandrews** [comment]
I'm confused about why this code isn't included in your tarball. The code is clearly on the github site, and is in the listed directory. What commands are you running to cause this error to appear?

**Comment by yurivict** [comment]
It downloads tarballs from https://www.smoldyn.org/, not from GitHub.

How do you make tarballs?

**Comment by ssandrews** [comment]
Sorry for the slow reply. I was initially thinking that you were downloading tarballs from github somehow. Anyhow, I just fixed the release script so that it will include the testcode.cpp file in future releases. Would it be helpful for you if I went ahead and created a new release now that includes this fix? If not, then I'll just wait until the next release. Clearly, the file is on github, so you can download it from there, too.

**Comment by yurivict** [comment]
Changing in the next release is fine, thank you!
