### ISSUE TITLE
Limit on the numbers of products in a reaction?

### ISSUE THREAD

**Issue by dilawar** [ssandrews/Smoldyn#18]
Consider the following statement in file `examples/S97_libsmoldyn/testcode/testcode.cpp`. 

```
smolAddReaction(sim, "r1", "rabbit", MSsoln, NULL, MSnone, N,
        (const char **)products, prodstates, 10);
```

`N=2` by default. When I increase `N` up to 20, things keep on working fine. When N goes larger than `30`, smoldyn could not build the model. It crashes in Python.

**Comment by dilawar** [comment]
Looking through the debugger, found macro `MAXPRODUCT` has the value 16. Can this value be increased?

Consider the following situation. A vesicle fuse with membrane and releases many neurotransmitters. If I model this as two reactions: `vesicle -> fused_vescile -> [trans, trans, ...]`. Sometimes I want more than 16 products (`trans` in this example). Currently, I have to create more chain reactions but would be cool if I can have more products in the API.

**Comment by dilawar** [comment]
The documentation is helpful.

> The constant MAXORDER is one more than the maximum reaction order that is permitted. For now, order 3 and higher reactions are not supported, although much of the code should function with any reaction order. High-order reactions may be supported in future versions. MAXPRODUCT is the maximum number of products that a reaction can have, which is only used at present in loading reactions from a configuration file. The enumerated type RevParam lists the possible “reversible parameter types” that are allowed.

Seems like it is just a limitation of the parser. I can tweak the API now.

**Comment by ssandrews** [comment]
Is there some maximum number of products that you think would be a good
limit? I chose 16 because that seemed like a reasonable number that was
bigger than people would likely use, but still small enough to not consume
excessive memory (several arrays are allocated to size MAXPRODUCT). If
there's some reason to make it bigger, then that can certainly be done. My
inclination would be to leave it as it is until someone has a compelling
need for a bigger value. At that point, either enlarge it, or rewrite the
code so that there's no limit and memory is allocated as needed.

-Steve

**Comment by dilawar** [comment]
> Is there some maximum number of products that you think would be a good limit? 

In usual cases, it is unlikely that more than 16 prds would be needed. I've rarely seen such reactions. 
For my specific case, I needed 1000 vesicles to be released from a fused vesicle. Which can also be done by a chain of 3 reactions each creating 10 prds. 

So its a question of average v/s corner case. I'd go with average unless the cost of supporting corner case is not large.
